export const TRIP = {
  title: 'ソウル3日間 旅ナビ',
  subtitle: '迷わない・忘れない・困ったらすぐ確認',
  timeZone: 'Asia/Seoul',
  dates: {
    start: '2026-08-28',
    end: '2026-08-30',
  },
  hotel: {
    name: 'ミリオレホテル ソウル明洞',
    addressJa: 'ソウル特別市 中区 退渓路115',
    addressKo: '서울특별시 중구 퇴계로 115',
    mapQuery: 'Migliore Hotel Seoul Myeongdong',
    note: '予約票に書かれたホテル名・住所を最優先してください。',
  },
  flight: {
    departure: '2026-08-30T16:05:00+09:00',
    airport: '仁川国際空港',
    terminal: '未登録',
    flightNumber: '未登録',
    arrivalTargetMinutes: 180,
    travelBufferMinutes: 80,
  },
  days: [
    {
      id: 'day1',
      date: '2026-08-28',
      label: '1日目',
      theme: '明洞・聖水・漢江',
      items: [
        {
          id: 'd1-hotel',
          time: '到着後',
          title: 'ホテルにチェックイン',
          placeId: 'hotel',
          type: 'hotel',
          note: '荷物を置いて、身軽になってから出発。',
        },
        {
          id: 'd1-porridge',
          time: '昼ごろ',
          title: '明洞でお粥',
          placeId: 'myeongdong',
          type: 'food',
          note: '店名は予約・候補リストで最終確認。',
        },
        {
          id: 'd1-seongsu',
          time: '午後',
          title: '聖水エリアを散策',
          placeId: 'seongsu',
          type: 'shopping',
          note: 'HAUS NOWHERE SEOUL、Point of View、29CM、POSETなど。全部回ろうとせず、近い店から。',
        },
        {
          id: 'd1-hangang',
          time: '夕方',
          title: '汝矣島漢江公園で休憩',
          placeId: 'yeouido',
          type: 'sightseeing',
          note: '夕方から夜景の時間がおすすめ。聖水からは距離があるので、移動時間を多めに。',
        },
        {
          id: 'd1-dinner',
          time: '夜',
          title: '明洞でチヂミの夕食',
          placeId: 'myeongdong',
          type: 'food',
          note: '混雑時は待ち時間を見込む。',
        },
        {
          id: 'd1-back',
          time: '夕食後',
          title: 'ホテルへ戻る',
          placeId: 'hotel',
          type: 'hotel',
          note: '翌日の予約時間を確認して充電。',
        },
      ],
    },
    {
      id: 'day2',
      date: '2026-08-29',
      label: '2日目',
      theme: '市場・美容・買い物',
      items: [
        {
          id: 'd2-jungbu',
          time: '午前',
          title: '中部市場で買い物',
          placeId: 'jungbu',
          type: 'shopping',
          note: 'ごま油など。液体は預け荷物に入れる前提で、漏れ防止袋も用意。',
        },
        {
          id: 'd2-gwangjang',
          time: '午前',
          title: '広蔵市場で食べ歩き',
          placeId: 'gwangjang',
          type: 'food',
          note: '一度に買いすぎず、少量ずつ。現金が必要な店もあります。',
        },
        {
          id: 'd2-naengmyeon',
          time: '昼',
          title: '冷麺ランチ',
          placeId: 'dongdaemun',
          type: 'food',
          note: '店名と住所は予約票・最新の候補を確認。',
        },
        {
          id: 'd2-beauty',
          time: '15:20 / 15:30',
          title: '弘大で美容予約',
          placeId: 'hongdae',
          type: 'appointment',
          fixed: true,
          note: 'ヘッドスパ組は15:20、肌管理組は15:30の想定。予約票の時刻と住所を最優先。',
        },
        {
          id: 'd2-juice',
          time: '施術後',
          title: 'ジュースで休憩',
          placeId: 'hongdae',
          type: 'break',
          note: '体調を確認して、急がず次へ。',
        },
        {
          id: 'd2-lotte',
          time: '夕方',
          title: 'ロッテマート ソウル駅店',
          placeId: 'lotte',
          type: 'shopping',
          note: '食品・お土産をまとめて購入。重い物は最後に。',
        },
        {
          id: 'd2-dinner',
          time: '夜',
          title: 'ヌンドンミナリで夕食',
          placeId: 'euljiro',
          type: 'food',
          note: '乙支路店の正確な店舗名・住所を予約票で確認。',
        },
        {
          id: 'd2-massage',
          time: '22:30',
          title: 'ティファニーマッサージ',
          placeId: 'myeongdong',
          type: 'appointment',
          fixed: true,
          note: '遅い時間のため、帰り道とホテルまでの移動を先に確認。',
        },
      ],
    },
    {
      id: 'day3',
      date: '2026-08-30',
      label: '3日目',
      theme: '弘大・帰国',
      warning: '10:00から約3時間の眉アートと、16:05発の国際線は時間に余裕がありません。空港到着目標は13:05です。予約の終了時刻・空港ターミナル・便名を必ず確認してください。',
      items: [
        {
          id: 'd3-checkout',
          time: '朝',
          title: 'チェックアウト',
          placeId: 'hotel',
          type: 'hotel',
          note: '忘れ物確認。パスポート・財布・充電器・薬。',
        },
        {
          id: 'd3-porridge',
          time: '朝',
          title: '明洞でお粥',
          placeId: 'myeongdong',
          type: 'food',
          note: '時間を使いすぎない。',
        },
        {
          id: 'd3-hongdae',
          time: '9:00ごろ',
          title: '弘大へ移動・荷物を預ける',
          placeId: 'hongdae',
          type: 'transport',
          note: '荷物の受取時間と保管場所を写真に残す。',
        },
        {
          id: 'd3-brow',
          time: '10:00',
          title: '眉アート',
          placeId: 'hongdae',
          type: 'appointment',
          fixed: true,
          note: '約3時間の予定。終了が12:00を超える場合は空港到着が遅くなる可能性が高いです。',
        },
        {
          id: 'd3-luggage',
          time: '施術後',
          title: '荷物を受け取る',
          placeId: 'hongdae',
          type: 'transport',
          note: '受取にかかる時間も見込む。',
        },
        {
          id: 'd3-airport',
          time: '目標 11:45出発',
          title: '仁川国際空港へ',
          placeId: 'incheon',
          type: 'airport',
          fixed: true,
          note: '空港到着目標は13:05。便名・ターミナルを確認してから移動。',
        },
        {
          id: 'd3-flight',
          time: '16:05',
          title: '仁川空港 発',
          placeId: 'incheon',
          type: 'airport',
          fixed: true,
          note: '搭乗口には搭乗時刻の30〜40分前までに到着。航空会社の案内を優先。',
        },
      ],
    },
  ],
  places: [
    {
      id: 'hotel',
      name: 'ミリオレホテル ソウル明洞',
      area: '明洞',
      category: 'ホテル',
      mapQuery: 'Migliore Hotel Seoul Myeongdong',
      addressJa: 'ソウル特別市 中区 退渓路115',
      addressKo: '서울특별시 중구 퇴계로 115',
      x: 48,
      y: 54,
    },
    {
      id: 'myeongdong',
      name: '明洞',
      area: '明洞',
      category: '食事・買い物',
      mapQuery: 'Myeongdong Station Seoul',
      addressJa: '地下鉄4号線 明洞駅周辺',
      addressKo: '명동역',
      x: 48,
      y: 48,
    },
    {
      id: 'seongsu',
      name: '聖水エリア',
      area: '聖水',
      category: 'カフェ・買い物',
      mapQuery: 'Seongsu Station Seoul',
      addressJa: '地下鉄2号線 聖水駅周辺',
      addressKo: '성수역',
      x: 82,
      y: 40,
    },
    {
      id: 'yeouido',
      name: '汝矣島漢江公園',
      area: '汝矣島',
      category: '公園',
      mapQuery: 'Yeouido Hangang Park Seoul',
      addressJa: '汝矣ナル駅周辺',
      addressKo: '여의도한강공원',
      x: 30,
      y: 72,
    },
    {
      id: 'jungbu',
      name: '中部市場',
      area: '乙支路',
      category: '市場',
      mapQuery: 'Jungbu Market Seoul',
      addressJa: '乙支路4街〜5街付近',
      addressKo: '서울중부시장',
      x: 63,
      y: 42,
    },
    {
      id: 'gwangjang',
      name: '広蔵市場',
      area: '鍾路',
      category: '市場',
      mapQuery: 'Gwangjang Market Seoul',
      addressJa: '鍾路5街駅周辺',
      addressKo: '광장시장',
      x: 68,
      y: 36,
    },
    {
      id: 'dongdaemun',
      name: '東大門エリア',
      area: '東大門',
      category: '食事',
      mapQuery: 'Dongdaemun Station Seoul',
      addressJa: '東大門駅・新堂駅周辺',
      addressKo: '동대문역',
      x: 74,
      y: 34,
    },
    {
      id: 'hongdae',
      name: '弘大入口',
      area: '弘大',
      category: '美容・荷物',
      mapQuery: 'Hongik University Station Seoul',
      addressJa: '地下鉄2号線・空港鉄道 弘大入口駅周辺',
      addressKo: '홍대입구역',
      x: 24,
      y: 46,
    },
    {
      id: 'lotte',
      name: 'ロッテマート ZETTAPLEX ソウル駅店',
      area: 'ソウル駅',
      category: '買い物',
      mapQuery: 'Lotte Mart ZETTAPLEX Seoul Station',
      addressJa: 'ソウル駅に隣接',
      addressKo: '롯데마트 제타플렉스 서울역점',
      x: 40,
      y: 52,
    },
    {
      id: 'euljiro',
      name: '乙支路3街',
      area: '乙支路',
      category: '食事',
      mapQuery: 'Euljiro 3-ga Station Seoul',
      addressJa: '地下鉄2号線・3号線 乙支路3街駅周辺',
      addressKo: '을지로3가역',
      x: 58,
      y: 46,
    },
    {
      id: 'gwanghwamun',
      name: '光化門・清渓川',
      area: '光化門',
      category: '観光',
      mapQuery: 'Gwanghwamun Square Seoul',
      addressJa: '光化門駅・市庁駅周辺',
      addressKo: '광화문광장',
      x: 47,
      y: 31,
    },
    {
      id: 'incheon',
      name: '仁川国際空港',
      area: '仁川',
      category: '空港',
      mapQuery: 'Incheon International Airport',
      addressJa: 'ターミナルは航空券で確認',
      addressKo: '인천국제공항',
      x: 6,
      y: 82,
    },
  ],
  shopping: [
    { id: 'sesame-oil', text: 'ごま油', group: '食品' },
    { id: 'seaweed', text: '韓国のり', group: '食品' },
    { id: 'snacks', text: 'お菓子・ラーメン', group: '食品' },
    { id: 'souvenirs', text: 'お土産', group: '買い物' },
    { id: 'cosmetics', text: 'コスメ・スキンケア', group: '美容' },
    { id: 'keyholder', text: '雑貨・キーホルダー', group: '買い物' },
    { id: 'leak-bag', text: '液体用の漏れ防止袋', group: '準備' },
  ],
  packing: [
    { id: 'passport', text: 'パスポート' },
    { id: 'eticket', text: '航空券・Eチケット' },
    { id: 'tmoney', text: 'T-moneyカード' },
    { id: 'battery', text: 'モバイルバッテリー' },
    { id: 'medicine', text: '常備薬・目薬' },
    { id: 'camera', text: 'カメラ・スマホ' },
    { id: 'cash', text: '現金（ウォン）' },
    { id: 'card', text: 'クレジットカード' },
  ],
  helpIntents: [
    {
      id: 'lost',
      label: '道に迷った',
      emoji: '🧭',
      examples: ['道に迷った。今いる場所がわからない。目的地まで行きたい。', '駅の出口を間違えた。ホテルへ戻りたい。'],
      answer: {
        title: 'まず安全な場所で止まる',
        steps: ['歩きながら操作せず、駅・コンビニ・ホテルの入口で止まる。', '下の「ホテルの地図」か、今日の予定にある「地図を開く」を押す。', 'まだ分からなければ1330に電話し、日本語を希望すると伝える。'],
        actions: ['hotelMap', 'call1330'],
      },
    },
    {
      id: 'late',
      label: '予約に遅れそう',
      emoji: '⏰',
      examples: ['予約に遅れそう。時間に間に合わない。', '電車が遅れて美容の予約時間に遅刻しそう。'],
      answer: {
        title: '予約先へ早めに連絡する',
        steps: ['予約票の電話・メッセージを開く。', '到着予定時刻を伝える。翻訳は普段使っている翻訳アプリを使う。', '移動中の走りすぎや無理な乗換えは避ける。'],
        actions: ['today'],
      },
    },
    {
      id: 'airport',
      label: '空港が心配',
      emoji: '✈️',
      examples: ['飛行機に間に合うか心配。空港へいつ出ればいい。', '空港のターミナルがわからない。帰国便が不安。'],
      answer: {
        title: '便名とターミナルを最初に確認',
        steps: ['Eチケットで便名・ターミナル・出発時刻を確認。', '空港到着目標は出発3時間前。', '「空港」画面の時刻を見て、遅れている場合は観光や買い物を増やさない。'],
        actions: ['airportMode', 'airportMap'],
      },
    },
    {
      id: 'payment',
      label: '支払いで困った',
      emoji: '💳',
      examples: ['カードが使えない。支払いができない。現金が必要。', 'T-moneyの残高が足りない。交通カードが使えない。'],
      answer: {
        title: '別の支払い方法を一つずつ試す',
        steps: ['クレジットカードをもう一枚試す。', '市場などでは現金を使う。', 'T-moneyは駅やコンビニで現金チャージする。'],
        actions: [],
      },
    },
    {
      id: 'phone',
      label: 'スマホ・通信',
      emoji: '📱',
      examples: ['インターネットがつながらない。スマホの電池が少ない。', 'Wi-Fiが使えない。充電が切れそう。'],
      answer: {
        title: '電池を守って、通信を一度入れ直す',
        steps: ['低電力モードをオンにする。', '機内モードを10秒オンにしてから戻す。', 'つながらなければホテル・駅・カフェのWi-Fiを使う。'],
        actions: [],
      },
    },
    {
      id: 'sick',
      label: '体調が悪い',
      emoji: '🩹',
      examples: ['気分が悪い。お腹が痛い。熱がある。怪我をした。', 'めまいがする。歩けない。救急車を呼びたい。'],
      answer: {
        title: '無理に移動しない',
        steps: ['座れる安全な場所へ移動し、水分を少しずつ取る。', '重い症状・意識がおかしい・息苦しい場合は119。', '軽い症状でも一人で我慢せず、ホテルか同行者に連絡する。'],
        actions: ['call119', 'hotelMap'],
      },
    },
    {
      id: 'lost-item',
      label: '物をなくした',
      emoji: '👜',
      examples: ['財布をなくした。パスポートをなくした。スマホがない。', '電車や店に荷物を忘れた。盗まれたかもしれない。'],
      answer: {
        title: '最後に使った場所へすぐ連絡',
        steps: ['最後に見た場所・時刻・移動手段をメモする。', '盗難や危険を感じる場合は112。', 'パスポート紛失は日本大使館領事部にも連絡する。'],
        actions: ['call112', 'callEmbassy'],
      },
    },
    {
      id: 'toilet',
      label: 'トイレを探したい',
      emoji: '🚻',
      examples: ['トイレはどこ。急いでトイレに行きたい。', '近くのトイレを探している。'],
      answer: {
        title: '駅・百貨店・大型カフェを探す',
        steps: ['地下鉄駅の改札内外を確認する。', '百貨店・ホテル・大型商業施設を使う。', '急ぐ場合は近くの店員に翻訳画面を見せる。'],
        actions: [],
      },
    },
    {
      id: 'taxi',
      label: 'タクシーで困った',
      emoji: '🚕',
      examples: ['タクシーに乗りたい。運転手に場所が伝わらない。', 'ホテルの住所を見せたい。タクシーが来ない。'],
      answer: {
        title: '住所を画面で見せる',
        steps: ['「ホテルを見せる」を開き、韓国語の住所を大きく表示する。', '乗車前に目的地が合っているか地図で確認。', '料金やトラブルで困ったら1330へ相談する。'],
        actions: ['showHotel', 'call1330'],
      },
    },
    {
      id: 'food',
      label: '食事・アレルギー',
      emoji: '🍽️',
      examples: ['食べ物のアレルギーが心配。辛すぎる。注文できない。', '何が入っているかわからない。体に合わない食べ物を避けたい。'],
      answer: {
        title: '分からない物は無理に食べない',
        steps: ['アレルギーがある場合は翻訳アプリで具体的な食材名を見せる。', '確認できない料理は避ける。', '息苦しさ・全身のじんましんなど重い症状は119。'],
        actions: ['call119'],
      },
    },
    {
      id: 'safety',
      label: '怖い・危険',
      emoji: '🛡️',
      examples: ['怖い人がいる。危険を感じる。つきまとわれている。', '夜道が怖い。助けてほしい。警察を呼びたい。'],
      answer: {
        title: '人の多い明るい場所へ移動',
        steps: ['コンビニ・ホテル・駅員のいる場所へ入る。', '危険が続く場合は112。', '同行者に現在地を送り、一人で戻ろうとしない。'],
        actions: ['call112', 'hotelMap'],
      },
    },
    {
      id: 'shopping',
      label: '買い物を確認',
      emoji: '🛍️',
      examples: ['何を買う予定だったか忘れた。買い物リストを見たい。', 'お土産の買い忘れがないか確認したい。'],
      answer: {
        title: '買い物リストを一つずつ確認',
        steps: ['「買い物」画面を開く。', '重い物・液体は最後に買う。', '液体は漏れ防止をして預け荷物へ。航空会社の規則を優先。'],
        actions: ['shopping'],
      },
    },
  ],
  contacts: [
    { id: 'police', name: '警察', number: '112', note: '事件・危険・盗難' },
    { id: 'ambulance', name: '救急・消防', number: '119', note: '急病・けが・火事' },
    { id: 'tourist', name: '観光案内・通訳', number: '1330', note: '日本語の観光案内・通訳相談' },
    { id: 'embassy', name: '在韓国日本大使館 領事部', number: '02-739-7400', note: 'パスポート紛失など' },
  ],
};
