import { initRegionSelector, resolveChainContext } from './region.js?v=20260825-store';
const ICON={
 sushiro:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 18h40L40 28H20zM15 31h34L38 41H22zM20 44h24L34 54H30z" fill="currentColor"/></svg>',
 hamazushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M8 37c10-20 19-21 28-7 8-9 15-7 20 3-11-5-17 2-22 8-8 9-18 8-26-4z" fill="currentColor"/><path d="M14 24c9-12 17-12 25-2-8-3-14 1-18 7z" fill="currentColor" opacity=".55"/></svg>',
 kurasushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 7 57 32 32 57 7 32 32 7zm0 10L17 32l15 15 15-15-15-15zm0 7 8 8-8 8-8-8 8-8z" fill="currentColor"/></svg>',
 kappasushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M10 16h44L44 25H20z" fill="#e83b32"/><path d="M14 28h36L42 37H22z" fill="#f08a28"/><path d="M18 40h28L39 49H25z" fill="#f6c33a"/></svg>',
 uobei:'<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="5"><circle cx="32" cy="32" r="8"/><path d="M32 7c8 0 10 8 7 15 7-5 15-1 17 6 2 8-5 12-13 11 6 5 4 14-3 18-7 4-14-2-15-10-3 8-12 10-18 5-6-5-3-14 5-17-8-1-13-8-10-15 3-7 12-8 18-3-4-7 0-15 12-10z"/></g></svg>'
};
const META={sushiro:{name:'スシロー',icon:ICON.sushiro,color:'#e3262e',soft:'#48171a'},hamazushi:{name:'はま寿司',icon:ICON.hamazushi,color:'#1687d9',soft:'#102d43'},kurasushi:{name:'くら寿司',icon:ICON.kurasushi,color:'#9f2430',soft:'#35171d'},kappasushi:{name:'かっぱ寿司',icon:ICON.kappasushi,color:'#49a942',soft:'#17341b'},uobei:{name:'魚べい',icon:ICON.uobei,color:'#f2a900',soft:'#493510'}};
let data=null,location={prefecture:'愛知県',city:'豊橋市',prefectureCode:'23'},active='all';
const cards=document.querySelector('#cards'),summary=document.querySelector('#summary'),updated=document.querySelector('#updatedAt'),refresh=document.querySelector('#refreshBtn'),highlights=document.querySelector('#todayHighlights'),todayDate=document.querySelector('#todayDate');
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const dateKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fmt=iso=>iso?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(new Date(`${iso}T00:00:00+09:00`)):null;
function period(f){return f.startDate&&f.endDate?`${fmt(f.startDate)} 〜 ${fmt(f.endDate)}`:f.startDate?`${fmt(f.startDate)} 〜 なくなり次第終了等`:'販売期間は公式情報で確認';}
function remaining(end){if(!end)return'期間限定';const n=Math.round((new Date(`${end}T00:00:00+09:00`)-new Date(`${dateKey()}T00:00:00+09:00`))/86400000);return n<0?'終了確認中':n===0?'本日まで':n<=3?`あと${n}日`:'開催中';}
function ctx(f){return resolveChainContext(f.chain,location);}
function valid(f){const c=ctx(f),today=dateKey();return(f.items||[]).filter(i=>i.saleStatus!=='ended'&&(!i.endDate||i.endDate>=today)&&(!(i.availability?.regionCodes?.length)||!c.value||i.availability.regionCodes.includes(c.value)));}
function priceText(f,i){if(i.price==null)return'価格確認';const n=`${Number(i.price).toLocaleString('ja-JP')}円`,c=ctx(f);if(f.chain==='hamazushi'&&c.verified)return n;if(f.dataScope==='national_official_release')return`公式掲載 ${n}`;return c.storeVerified?`店舗参考 ${n}`:`参考 ${n}`;}
function context(f){const c=ctx(f);return `<div class="region-context ${c.verified?'verified':'unverified'}"><strong>📍 ${esc(location.prefecture)} ${esc(location.city)}</strong><span>${esc(c.label)}</span><small>${esc(c.note)}</small></div>`;}
function scope(f){if(f.dataScope==='national_official_release')return'全国向け公式発表が基準です。表示価格は公式発表価格で、選択店舗の確定価格ではない場合があります。';if(f.dataScope==='reference_store_menu_overlay')return'全国フェアと店舗掲載を分離。選択地域の代表店舗が確認できた場合でも、現在の商品価格は店舗別メニュー更新まで参考表示です。';return'公式メニューを基準に表示。地域・店舗差は確認できた情報だけ反映します。';}
function visual(f,m){return `<div class="fair-visual">${f.imageUrl?`<img src="${esc(f.imageUrl)}" alt="${esc(m.name)} ${esc(f.fairName||'フェア')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<div class="visual-shade"></div><div class="chain-mark">${m.icon}</div><div class="visual-copy"><strong>${esc(m.name)}</strong><span>${esc(f.fairName||'期間限定メニュー')}</span><small>${esc(period(f))}</small></div><b>${esc(remaining(f.endDate))}</b></div>`;}
function renderHighlights(chains){todayDate.textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short'}).format(new Date());highlights.innerHTML=`<div class="highlight-group"><div class="highlight-title"><span>🍣</span><strong>${esc(location.prefecture)} ${esc(location.city)}で表示中</strong></div>${chains.slice(0,3).map(f=>{const m=META[f.chain],i=valid(f)[0];return `<a class="highlight-card" href="#card-${f.chain}"><div><span class="highlight-chain" style="color:${m.color}">${m.name}</span><strong>${esc(f.fairName||'期間限定メニュー')}</strong>${i?`<small>${esc(i.name)}${i.price!=null?` ・ ${priceText(f,i)}`:''}</small>`:''}</div><span class="highlight-deadline">${remaining(f.endDate)}</span></a>`}).join('')}</div>`;}
function render(){if(!data)return;const all=data.chains||[],shown=all.filter(f=>active==='all'||f.chain===active);renderHighlights(all);summary.innerHTML=all.map(f=>{const m=META[f.chain]||{name:f.chain,icon:ICON.kurasushi,color:'#888',soft:'#222'},items=valid(f);return `<a class="chain-summary chain-${f.chain}" href="#card-${f.chain}" style="--chain-color:${m.color};--chain-soft:${m.soft}"><div class="chain-summary-media">${f.imageUrl?`<img src="${esc(f.imageUrl)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<span class="chain-summary-fallback">${m.icon}</span></div><div class="chain-summary-body"><div><strong>${m.name}</strong><span>${items.length}品</span></div><small>${esc(f.fairName||'開催中フェア')}</small></div><span class="chain-summary-arrow">↓</span></a>`}).join('');cards.innerHTML=shown.map(f=>{const m=META[f.chain]||{name:f.chain,icon:ICON.kurasushi,color:'#888',soft:'#222'},c=ctx(f),items=valid(f),visible=items.slice(0,10),lis=visible.length?`<ul class="items">${visible.map(i=>`<li class="item"><span class="item-name">${esc(i.name)}${i.startDate||i.endDate?`<small class="item-period">${i.startDate?fmt(i.startDate):''}${i.startDate&&i.endDate?'〜':''}${i.endDate?fmt(i.endDate):''}</small>`:''}</span><span class="price">${esc(priceText(f,i))}</span></li>`).join('')}</ul>${items.length>10?`<div class="more">ほか ${items.length-10} 品</div>`:''}`:`<div class="empty">個別商品の取得は確認中です。取得失敗を販売終了とは扱いません。</div>`;const storeUrl=c.officialUrl||f.officialActionUrl||f.storeUrl||'#';return `<article id="card-${f.chain}" class="card chain-${f.chain}" style="--chain-color:${m.color};--chain-soft:${m.soft}">${visual(f,m)}${context(f)}<p class="price-note scope-note">${esc(scope(f))}</p>${f.status!=='ok'?`<div class="error-banner">${esc(f.message||'公式情報の一部を取得できませんでした。')}</div>`:''}${lis}${f.priceNote?`<p class="price-note">※ ${esc(f.priceNote)}</p>`:''}<div class="actions"><a class="primary" href="${esc(f.sourceUrl||'#')}" target="_blank" rel="noopener">公式フェア</a><a class="secondary" href="${esc(storeUrl)}" target="_blank" rel="noopener">店舗・予約を<br>公式で確認</a></div></article>`}).join('');}
async function load(){refresh.disabled=true;refresh.textContent='↻ 読込中';try{const r=await fetch(`./data/fairs.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();updated.textContent=`最終更新 ${new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(new Date(data.updatedAt))}`;render();}catch(e){cards.innerHTML=`<div class="error-banner">${esc(e.message)}</div>`;}finally{refresh.disabled=false;refresh.textContent='↻ 更新';}}
document.querySelector('#filters')?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;active=b.dataset.chain;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render();});refresh?.addEventListener('click',load);location=await initRegionSelector({onApply:async next=>{location=next;render();}});await load();
