import { initRegionSelector, resolveChainContext } from './region.js?v=20260825-regionux';
const META={sushiro:{name:'スシロー',mark:'ス',color:'#e3262e',soft:'#48171a'},hamazushi:{name:'はま寿司',mark:'はま',color:'#1687d9',soft:'#102d43'},kurasushi:{name:'くら寿司',mark:'くら',color:'#9f2430',soft:'#35171d'},kappasushi:{name:'かっぱ寿司',mark:'か',color:'#49a942',soft:'#17341b'},uobei:{name:'魚べい',mark:'魚',color:'#f2a900',soft:'#493510'}};
let data=null,location={prefecture:'愛知県',city:'豊橋市',prefectureCode:'23'},active='all';
const cards=document.querySelector('#cards'),summary=document.querySelector('#summary'),updated=document.querySelector('#updatedAt'),refresh=document.querySelector('#refreshBtn'),highlights=document.querySelector('#todayHighlights'),todayDate=document.querySelector('#todayDate');
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const dateKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fmt=iso=>iso?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(new Date(`${iso}T00:00:00+09:00`)):null;
function period(f){return f.startDate&&f.endDate?`${fmt(f.startDate)} 〜 ${fmt(f.endDate)}`:f.startDate?`${fmt(f.startDate)} 〜 なくなり次第終了等`:'販売期間は公式情報で確認';}
function remaining(end){if(!end)return'期間限定';const n=Math.round((new Date(`${end}T00:00:00+09:00`)-new Date(`${dateKey()}T00:00:00+09:00`))/86400000);return n<0?'終了確認中':n===0?'本日まで':n<=3?`あと${n}日`:'開催中';}
function valid(f){const ctx=resolveChainContext(f.chain,location),today=dateKey();return(f.items||[]).filter(i=>i.saleStatus!=='ended'&&(!i.endDate||i.endDate>=today)&&(!(i.availability?.regionCodes?.length)||!ctx.value||i.availability.regionCodes.includes(ctx.value)));}
function regionalPriceIsVerified(f){const ctx=resolveChainContext(f.chain,location);return f.dataScope==='national_official_release'||(f.chain==='hamazushi'&&ctx.verified);}
function priceText(f,i){if(i.price==null)return'価格確認';return regionalPriceIsVerified(f)?`${Number(i.price).toLocaleString('ja-JP')}円`:`参考 ${Number(i.price).toLocaleString('ja-JP')}円`;}
function context(f){const c=resolveChainContext(f.chain,location);return `<div class="region-context ${c.verified?'verified':'unverified'}"><strong>📍 ${esc(location.prefecture)} ${esc(location.city)}</strong><span>${esc(c.label)}</span><small>${esc(c.note)}</small></div>`;}
function scope(f){if(f.dataScope==='national_official_release')return'全国向け公式発表を基準に表示。店舗ごとの価格・取扱い・売切れは公式で確認してください。';if(f.dataScope==='reference_store_menu_overlay')return'全国フェアと代表店舗メニューを分離。代表店舗価格は選択地域の確定価格として扱いません。';return'公式メニューを基準に表示。地域・店舗差は確認できた情報だけ反映します。';}
function visual(f,m){return `<div class="fair-visual">${f.imageUrl?`<img src="${esc(f.imageUrl)}" alt="${esc(m.name)} ${esc(f.fairName||'フェア')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<div class="visual-shade"></div><div class="chain-mark">${esc(m.mark)}</div><div class="visual-copy"><strong>${esc(m.name)}</strong><span>${esc(f.fairName||'期間限定メニュー')}</span><small>${esc(period(f))}</small></div><b>${esc(remaining(f.endDate))}</b></div>`;}
function renderHighlights(chains){todayDate.textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short'}).format(new Date());highlights.innerHTML=`<div class="highlight-group"><div class="highlight-title"><span>🍣</span><strong>${esc(location.prefecture)} ${esc(location.city)}で表示中</strong></div>${chains.slice(0,3).map(f=>{const m=META[f.chain],i=valid(f)[0];return `<a class="highlight-card" href="#card-${f.chain}"><div><span class="highlight-chain" style="color:${m.color}">${m.name}</span><strong>${esc(f.fairName||'期間限定メニュー')}</strong>${i?`<small>${esc(i.name)}${i.price!=null?` ・ ${priceText(f,i)}`:''}</small>`:''}</div><span class="highlight-deadline">${remaining(f.endDate)}</span></a>`}).join('')}</div>`;}
function render(){if(!data)return;const all=data.chains||[],shown=all.filter(f=>active==='all'||f.chain===active);renderHighlights(all);summary.innerHTML=all.map(f=>{const m=META[f.chain]||{name:f.chain,mark:'寿',color:'#888',soft:'#222'},items=valid(f);return `<a class="chain-summary chain-${f.chain}" href="#card-${f.chain}" style="--chain-color:${m.color};--chain-soft:${m.soft}"><div class="chain-summary-media">${f.imageUrl?`<img src="${esc(f.imageUrl)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<span class="chain-summary-fallback">${esc(m.mark)}</span></div><div class="chain-summary-body"><div><strong>${m.name}</strong><span>${items.length}品</span></div><small>${esc(f.fairName||'開催中フェア')}</small></div><span class="chain-summary-arrow">↓</span></a>`}).join('');cards.innerHTML=shown.map(f=>{const m=META[f.chain]||{name:f.chain,mark:'寿',color:'#888',soft:'#222'},items=valid(f),visible=items.slice(0,10),lis=visible.length?`<ul class="items">${visible.map(i=>`<li class="item"><span class="item-name">${esc(i.name)}${i.startDate||i.endDate?`<small class="item-period">${i.startDate?fmt(i.startDate):''}${i.startDate&&i.endDate?'〜':''}${i.endDate?fmt(i.endDate):''}</small>`:''}</span><span class="price">${esc(priceText(f,i))}</span></li>`).join('')}</ul>${items.length>10?`<div class="more">ほか ${items.length-10} 品</div>`:''}`:`<div class="empty">個別商品の取得は確認中です。取得失敗を販売終了とは扱いません。</div>`;return `<article id="card-${f.chain}" class="card chain-${f.chain}" style="--chain-color:${m.color};--chain-soft:${m.soft}">${visual(f,m)}${context(f)}<p class="price-note scope-note">${esc(scope(f))}</p>${f.status!=='ok'?`<div class="error-banner">${esc(f.message||'公式情報の一部を取得できませんでした。')}</div>`:''}${lis}${f.priceNote?`<p class="price-note">※ ${esc(f.priceNote)}</p>`:''}<div class="actions"><a class="primary" href="${esc(f.sourceUrl||'#')}" target="_blank" rel="noopener">公式フェア</a><a class="secondary" href="${esc(f.officialActionUrl||f.storeUrl||'#')}" target="_blank" rel="noopener">混雑・予約を<br>公式で確認</a></div></article>`}).join('');}
async function load(){refresh.disabled=true;refresh.textContent='↻ 読込中';try{const r=await fetch(`./data/fairs.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();updated.textContent=`最終更新 ${new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(new Date(data.updatedAt))}`;render();}catch(e){cards.innerHTML=`<div class="error-banner">${esc(e.message)}</div>`;}finally{refresh.disabled=false;refresh.textContent='↻ 更新';}}
document.querySelector('#filters')?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;active=b.dataset.chain;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render();});refresh?.addEventListener('click',load);location=await initRegionSelector({onApply:async next=>{location=next;render();}});await load();
