import { initRegionSelector, resolveChainContext } from './region.js?v=20260826-data1';

const ICON={
  sushiro:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 18h40L40 28H20zM15 31h34L38 41H22zM20 44h24L34 54H30z" fill="currentColor"/></svg>',
  hamazushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M8 37c10-20 19-21 28-7 8-9 15-7 20 3-11-5-17 2-22 8-8 9-18 8-26-4z" fill="currentColor"/><path d="M14 24c9-12 17-12 25-2-8-3-14 1-18 7z" fill="currentColor" opacity=".55"/></svg>',
  kurasushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 7 57 32 32 57 7 32 32 7zm0 10L17 32l15 15 15-15-15-15zm0 7 8 8-8 8-8-8 8-8z" fill="currentColor"/></svg>',
  kappasushi:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M10 16h44L44 25H20z" fill="#e83b32"/><path d="M14 28h36L42 37H22z" fill="#f08a28"/><path d="M18 40h28L39 49H25z" fill="#f6c33a"/></svg>',
  uobei:'<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="5"><circle cx="32" cy="32" r="8"/><path d="M32 7c8 0 10 8 7 15 7-5 15-1 17 6 2 8-5 12-13 11 6 5 4 14-3 18-7 4-14-2-15-10-3 8-12 10-18 5-6-5-3-14 5-17-8-1-13-8-10-15 3-7 12-8 18-3-4-7 0-15 12-10z"/></g></svg>',
  totomaru:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M9 33c9-13 22-18 35-10l11-7-2 15 2 15-11-7c-13 8-26 3-35-6z" fill="currentColor"/><circle cx="24" cy="29" r="3" fill="#fff"/></svg>',
  musashimaru:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M11 48V16h9l12 18 12-18h9v32h-9V30L32 47 20 30v18z" fill="currentColor"/><path d="M8 53c15-7 33-7 48 0" fill="none" stroke="currentColor" stroke-width="4"/></svg>',
  tokubei:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 8c12 7 20 17 22 30-8-5-15-7-22-7s-14 2-22 7C12 25 20 15 32 8z" fill="currentColor"/><path d="M18 43h28M24 50h16" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg>'
};
const META={
  sushiro:{name:'スシロー',icon:ICON.sushiro,color:'#e3262e',soft:'#48171a',group:'national'},hamazushi:{name:'はま寿司',icon:ICON.hamazushi,color:'#1687d9',soft:'#102d43',group:'national'},kurasushi:{name:'くら寿司',icon:ICON.kurasushi,color:'#9f2430',soft:'#35171d',group:'national'},kappasushi:{name:'かっぱ寿司',icon:ICON.kappasushi,color:'#49a942',soft:'#17341b',group:'national'},uobei:{name:'魚べい',icon:ICON.uobei,color:'#f2a900',soft:'#493510',group:'national'},totomaru:{name:'魚魚丸',icon:ICON.totomaru,color:'#e35b35',soft:'#4a2219',group:'local_tokai'},musashimaru:{name:'武蔵丸',icon:ICON.musashimaru,color:'#da7b33',soft:'#3e2518',group:'local_tokai'},tokubei:{name:'にぎりの徳兵衛',icon:ICON.tokubei,color:'#b93a48',soft:'#401923',group:'local_tokai'}
};
let data=null;let location={prefecture:'愛知県',city:'豊橋市',prefectureCode:'23'};let active='all';const expandedChains=new Set();
const cardsNational=document.querySelector('#cardsNational'),cardsLocal=document.querySelector('#cardsLocal'),nationalGroup=document.querySelector('#nationalGroup'),localGroup=document.querySelector('#localTokaiGroup'),quickNational=document.querySelector('#chainQuickNavNational'),quickLocal=document.querySelector('#chainQuickNavLocal'),updated=document.querySelector('#updatedAt'),refresh=document.querySelector('#refreshBtn');
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
const dateKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fmt=iso=>iso?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(new Date(`${iso}T00:00:00+09:00`)):null;
const groupOf=f=>f.group||META[f.chain]?.group||'national';
function period(f){if(f.startDate&&f.endDate)return `${fmt(f.startDate)} 〜 ${fmt(f.endDate)}`;if(f.startDate)return `${fmt(f.startDate)} 〜`;return '販売期間は公式情報で確認';}
function remaining(end){if(!end)return '期間限定';const n=Math.round((new Date(`${end}T00:00:00+09:00`)-new Date(`${dateKey()}T00:00:00+09:00`))/86400000);if(n<0)return '終了確認中';if(n===0)return '本日まで';if(n<=3)return `あと${n}日`;return '開催中';}
function ctx(f){return resolveChainContext(f.chain,location);}

function sushiroLocalItem(f,item){
  if(f.chain!=='sushiro')return null;
  const local=ctx(f).store?.localFairItems||[];
  return local.find(x=>clean(x.name)===clean(item.name))||null;
}
function sourceItems(f){
  const base=Array.isArray(f.items)?f.items:[];
  if(f.chain!=='sushiro')return base;
  return base.map(item=>{
    const local=sushiroLocalItem(f,item);
    return {...item,regionalPrice:local?.price??null,regionalListed:Boolean(local),regionalStoreItem:local||null};
  });
}
function valid(f){const c=ctx(f),today=dateKey();return sourceItems(f).filter(i=>i.saleStatus!=='ended'&&(!i.endDate||i.endDate>=today)&&(!(i.availability?.regionCodes?.length)||!c.value||i.availability.regionCodes.includes(c.value)));}
function priceText(f,i){
  const c=ctx(f);
  if(f.chain==='sushiro'){
    if(i.regionalPrice!=null){const n=`${Number(i.regionalPrice).toLocaleString('ja-JP')}円`;return c.store?.match==='same_prefecture'?`県内参考 ${n}`:`地域価格 ${n}`;}
    if(i.price!=null)return `全国基準 ${Number(i.price).toLocaleString('ja-JP')}円`;
    return '価格確認';
  }
  if(i.price==null)return '価格確認';const n=`${Number(i.price).toLocaleString('ja-JP')}円`;
  if(f.chain==='hamazushi'&&c.verified)return `地域目安 ${n}`;if(groupOf(f)==='local_tokai')return `公式掲載 ${n}`;if(f.dataScope==='national_official_release')return `公式掲載 ${n}`;return c.storeVerified?`店舗参考 ${n}`:`参考 ${n}`;
}
function context(f){const c=ctx(f),local=groupOf(f)==='local_tokai',mode=c.approximate?'unverified':c.verified?'verified':'unverified';const badge=local&&!c.availableInSelectedArea?'店舗なし':c.storeVerified?'地域反映済み':'地域目安';const extra=local&&!c.availableInSelectedArea?' local-store-missing':'';return `<div class="region-context ${mode}${extra}"><div class="region-context-title"><strong>📍 ${esc(location.prefecture)} ${esc(location.city)}向け</strong><span>${esc(badge)}</span></div><span>${esc(c.label)}</span><small>${esc(c.note)}</small></div>`;}
function scope(f){const c=ctx(f);if(groupOf(f)==='local_tokai'){if(c.availableInSelectedArea&&c.store)return `選択地域の公式店舗「${c.store.storeName}」を参照。フェア情報はチェーン公式情報を基準に表示します。`;return '選択市区町村では公式店舗を確認できません。遠方店舗を代表店にせず、フェア情報と公式店舗検索への導線だけを表示します。';}if(f.chain==='sushiro')return c.store?`全国フェア商品を基準に、${c.store.storeName}の店舗別価格・掲載状況だけを地域overlayとして表示します。店舗ページから消えても全国商品は即削除しません。`:'全国フェア商品を基準に表示します。代表店舗がない場合も全国商品は保持します。';if(f.dataScope==='national_official_release')return '全国向け公式発表が基準です。地域・店舗により価格や取扱いが異なる場合があります。';return '公式フェア情報を基準に、地域差は代表値で簡易表示します。';}
function visualImage(f){const c=ctx(f);if(f.chain==='sushiro'&&c.store?.representativeImageUrl)return c.store.representativeImageUrl;return f.representativeImageUrl||f.imageUrl||null;}
function representativeItem(f,items){if(!items.length)return null;const preferred=f.representativeImageProduct;return(preferred&&items.find(i=>i.name===preferred))||items[0];}
function visual(f,m,itemCount){const items=valid(f),img=visualImage(f),heroProduct=representativeItem(f,items)?.name||f.representativeImageProduct||null,c=ctx(f),localMissing=groupOf(f)==='local_tokai'&&!c.availableInSelectedArea;const state=localMissing?'店舗なし':remaining(f.endDate);return `<div class="fair-visual">${img?`<img src="${esc(img)}" alt="${esc(m.name)} ${esc(heroProduct||f.fairName||'フェア')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<div class="visual-shade"></div><div class="chain-mark">${m.icon}</div><div class="visual-copy"><strong>${esc(m.name)}</strong><span>${esc(f.fairName||'期間限定メニュー')}</span><small>${esc(period(f))}</small>${heroProduct?`<em>代表メニュー：${esc(heroProduct)}</em>`:''}</div><div class="visual-badges"><b>${esc(state)}</b><span>${itemCount}品</span></div></div>`;}
function actionLinks(f,c){let primaryUrl=f.sourceUrl||'#',primaryLabel='公式フェア・メニュー';if(f.chain==='sushiro'&&c.store?.menuUrl){primaryUrl=c.store.menuUrl;primaryLabel='地域メニューを公式で確認';}else if(f.chain==='hamazushi')primaryLabel='地域メニューを公式で確認';else if(['kurasushi','kappasushi','uobei','tokubei'].includes(f.chain))primaryLabel='公式フェアを見る';else if(['totomaru','musashimaru'].includes(f.chain))primaryLabel='公式メニューを見る';const secondaryUrl=c.officialUrl||f.officialActionUrl||f.storeUrl||'#';const secondaryLabel=groupOf(f)==='local_tokai'&&!c.availableInSelectedArea?'近隣店舗を公式で確認':'店舗・予約を公式で確認';return{primaryUrl,primaryLabel,secondaryUrl,secondaryLabel};}
function pickupText(f,item){if(item)return `ピックアップ：${esc(item.name)}${item.price!=null||item.regionalPrice!=null?` <strong>${esc(priceText(f,item))}</strong>`:''}`;if(f.chain==='musashimaru')return 'ピックアップ：公式おすすめをメニューで確認';if(f.chain==='totomaru')return 'ピックアップ：旬ネタを公式メニューで確認';return f.status==='warning'?'公式サイトで確認':'商品情報を確認中';}
function quickCard(f){const m=META[f.chain]||{name:f.chain,icon:ICON.kurasushi,color:'#888',soft:'#222'},items=valid(f),item=representativeItem(f,items),img=visualImage(f),c=ctx(f),localMissing=groupOf(f)==='local_tokai'&&!c.availableInSelectedArea;const status=localMissing?'店舗なし':f.status==='ok'?(items.length?remaining(f.endDate):'情報あり'):'公式確認';const shortPeriod=f.endDate?`〜${fmt(f.endDate)}`:f.startDate?`${fmt(f.startDate)}〜`:'期間は公式で確認';return `<button type="button" class="quick-chain quick-${f.chain}" data-chain-jump="${esc(f.chain)}" style="--chain-color:${m.color};--chain-soft:${m.soft}" aria-label="${esc(m.name)}の詳細へ移動"><span class="quick-chain-photo">${img?`<img src="${esc(img)}" alt="${esc(m.name)}の代表メニュー" loading="eager" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<span class="quick-chain-mark">${m.icon}</span></span><span class="quick-chain-copy"><span class="quick-chain-top"><b>${esc(m.name)}</b><em>${esc(status)}</em></span><span class="quick-fair">${esc(f.fairName||'公式メニュー')}</span><small class="quick-pickup">${pickupText(f,item)}</small><small class="quick-period">${esc(shortPeriod)}${items.length?` ・ ${items.length}品掲載`:''}</small></span></button>`;}
function renderQuickCompare(all){if(quickNational)quickNational.innerHTML=all.filter(f=>groupOf(f)==='national').map(quickCard).join('');if(quickLocal)quickLocal.innerHTML=all.filter(f=>groupOf(f)==='local_tokai').map(quickCard).join('');}
function itemStatusNote(f,i){if(f.chain==='sushiro'&&i.scrapeStatus==='not_listed_reference_store')return `<small class="item-availability">代表店舗で未掲載・全国フェアとして保持</small>`;return '';}
function cardHtml(f){const m=META[f.chain]||{name:f.chain,icon:ICON.kurasushi,color:'#888',soft:'#222'},c=ctx(f),items=valid(f),expanded=expandedChains.has(f.chain),visible=expanded?items:items.slice(0,4),links=actionLinks(f,c);const list=visible.length?`<ul class="items">${visible.map(i=>`<li class="item"><span class="item-name">${esc(i.name)}${i.startDate||i.endDate?`<small class="item-period">${i.startDate?fmt(i.startDate):''}${i.startDate&&i.endDate?'〜':''}${i.endDate?fmt(i.endDate):''}</small>`:''}${itemStatusNote(f,i)}</span><span class="price">${esc(priceText(f,i))}</span></li>`).join('')}</ul>`:`<div class="empty">個別商品は推測せず、公式サイトで確認できる情報だけを表示しています。</div>`;const toggle=items.length>4?`<button type="button" class="product-toggle" data-expand-chain="${esc(f.chain)}" aria-expanded="${expanded}">${expanded?'商品を閉じる ▲':`全${items.length}件の商品を見る ▼`}</button>`:'';return `<article id="card-${f.chain}" class="card chain-${f.chain}" style="--chain-color:${m.color};--chain-soft:${m.soft}">${visual(f,m,items.length)}${context(f)}<p class="price-note scope-note">${esc(scope(f))}</p>${f.status!=='ok'?`<div class="error-banner">${esc(f.message||'公式情報の一部を取得できませんでした。')}</div>`:''}${list}${toggle}${f.priceNote?`<p class="price-note">※ ${esc(f.priceNote)}</p>`:''}<div class="actions"><a class="primary" href="${esc(links.primaryUrl)}" target="_blank" rel="noopener">${esc(links.primaryLabel)}</a><a class="secondary" href="${esc(links.secondaryUrl)}" target="_blank" rel="noopener">${esc(links.secondaryLabel)}</a></div></article>`;}
function render(){if(!data)return;const all=data.chains||[],shown=all.filter(f=>active==='all'||f.chain===active),national=shown.filter(f=>groupOf(f)==='national'),local=shown.filter(f=>groupOf(f)==='local_tokai');renderQuickCompare(all);if(cardsNational)cardsNational.innerHTML=national.map(cardHtml).join('');if(cardsLocal)cardsLocal.innerHTML=local.map(cardHtml).join('');nationalGroup?.classList.toggle('hidden',national.length===0);localGroup?.classList.toggle('hidden',local.length===0);}
function setActiveFilter(chain){active=chain;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.chain===chain));}
function jumpToChain(chain){let target=document.querySelector(`#card-${chain}`);if(!target){setActiveFilter('all');render();target=document.querySelector(`#card-${chain}`);}target?.scrollIntoView({behavior:'smooth',block:'start'});}
async function load(){refresh.disabled=true;refresh.textContent='↻ 読込中';try{const r=await fetch(`./data/fairs.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();updated.textContent=`最終更新 ${new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(new Date(data.updatedAt))}`;render();}catch(e){const html=`<div class="error-banner">${esc(e.message)}</div>`;if(cardsNational)cardsNational.innerHTML=html;if(cardsLocal)cardsLocal.innerHTML='';}finally{refresh.disabled=false;refresh.textContent='↻ 更新';}}
document.querySelector('#filters')?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;setActiveFilter(b.dataset.chain);render();});for(const nav of [quickNational,quickLocal])nav?.addEventListener('click',e=>{const b=e.target.closest('[data-chain-jump]');if(b)jumpToChain(b.dataset.chainJump);});for(const host of [cardsNational,cardsLocal])host?.addEventListener('click',e=>{const b=e.target.closest('[data-expand-chain]');if(!b)return;const chain=b.dataset.expandChain;if(expandedChains.has(chain))expandedChains.delete(chain);else expandedChains.add(chain);render();if(!expandedChains.has(chain))document.querySelector(`#card-${chain}`)?.scrollIntoView({behavior:'smooth',block:'start'});});refresh?.addEventListener('click',load);location=await initRegionSelector({onApply:async next=>{location=next;expandedChains.clear();render();}});await load();
