import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT=fileURLToPath(new URL('..',import.meta.url));
const PAGE_URL=process.argv[2];const REPORT_PATH=process.env.SMOKE_REPORT_PATH||null;const MAX_ATTEMPTS=12;const RETRY_DELAY_MS=5000;
if(!PAGE_URL)throw new Error('Usage: node scripts/verify-pages.mjs <page-url>');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const normalize=v=>String(v).replace(/\r\n/g,'\n').trimEnd();
function bust(url,a){const u=new URL(url);u.searchParams.set('__smoke',`${Date.now()}-${a}`);return u.href;}
async function fetchText(url,a){const r=await fetch(bust(url,a),{redirect:'follow',signal:AbortSignal.timeout(15000),headers:{accept:'text/html,application/json,text/plain,*/*;q=.5','cache-control':'no-cache',pragma:'no-cache'}});if(!r.ok)throw new Error(`${url} returned HTTP ${r.status}`);return r.text();}
async function fetchBinary(url,a){const r=await fetch(bust(url,a),{redirect:'follow',signal:AbortSignal.timeout(15000),headers:{accept:'image/webp,image/*;q=.9,*/*;q=.5','cache-control':'no-cache',pragma:'no-cache'}});if(!r.ok)throw new Error(`${url} returned HTTP ${r.status}`);return {type:r.headers.get('content-type')||'',bytes:new Uint8Array(await r.arrayBuffer())};}
const NATIONAL=['hamazushi','kappasushi','kurasushi','sushiro','uobei'];const LOCAL=['musashimaru','tokubei','totomaru'];
const freshness=(remote,local,label)=>{const r=Date.parse(remote),l=Date.parse(local);assert.ok(Number.isFinite(r),`${label} remote updatedAt invalid`);assert.ok(Number.isFinite(l),`${label} local updatedAt invalid`);assert.ok(r>=l,`${label} public data is older than this run (${remote} < ${local})`);};
function validateFairs(data){assert.equal(data?.schemaVersion,2);assert.equal(data?.timezone,'Asia/Tokyo');assert.ok(Date.parse(data?.updatedAt));assert.equal(data?.locationModel?.mode,'manual_prefecture_city');assert.equal(data?.locationModel?.gps,false);assert.ok(Array.isArray(data?.chains));const by=Object.fromEntries(data.chains.map(x=>[x.chain,x]));for(const id of [...NATIONAL,...LOCAL])assert.ok(by[id],`${id} fair data missing`);for(const id of LOCAL)assert.equal(by[id].group,'local_tokai',`${id} group must be local_tokai`);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());for(const chain of data.chains){assert.ok(Array.isArray(chain.items));assert.match(chain.officialActionUrl||'',/^https:\/\//);assert.ok(chain.regionalModel?.strategyKey);if(chain.campaigns!=null)assert.ok(Array.isArray(chain.campaigns));if(chain.endDate&&chain.endDate<today)assert.notEqual(chain.status,'ok');for(const item of chain.items){assert.ok(item?.name);assert.ok(['active','ended','unknown'].includes(item.saleStatus||'active'));assert.ok(item.scrapeStatus);if(item.endDate&&item.endDate<today)assert.notEqual(item.saleStatus,'active');}}
  const s=by.sushiro;assert.equal(s.nationalSourceOfTruth,true,'Sushiro national fair must be source of truth');assert.equal(s.referenceStoreOverlayOnly,true);for(const item of s.items){assert.ok('startDate' in item&&'endDate' in item,'Sushiro item dates must be retained');assert.ok(item.sourceUrl,'Sushiro item sourceUrl required');}
}
function findExact(catalog,chain,prefecture,municipality){return Object.values(catalog?.[chain]||{}).find(x=>x.prefecture===prefecture&&x.municipality===municipality)||null;}
function findCity(catalog,chain,prefecture,cityPrefix){return Object.values(catalog?.[chain]||{}).find(x=>x.prefecture===prefecture&&String(x.municipality||'').startsWith(cityPrefix))||null;}
function validateStores(data){assert.equal(data?.schemaVersion,1);assert.ok(data?.catalog&&typeof data.catalog==='object');for(const chain of [...NATIONAL,...LOCAL])assert.ok(data.catalog[chain]&&typeof data.catalog[chain]==='object',`${chain} store catalog missing`);const ss=findExact(data.catalog,'sushiro','北海道','札幌市中央区'),ts=findExact(data.catalog,'sushiro','愛知県','豊橋市');assert.equal(ss?.storeId,'2575');assert.equal(ss?.menuAreaCode,'883');assert.equal(ts?.storeId,'142');assert.equal(ts?.menuAreaCode,'179');assert.notEqual(ss.menuUrl,ts.menuUrl);const hh=findExact(data.catalog,'hamazushi','北海道','札幌市中央区'),th=findExact(data.catalog,'hamazushi','愛知県','豊橋市');assert.equal(hh?.storeId,'4460');assert.equal(hh?.regionCode,'hokkaido');assert.equal(th?.storeId,'4208');assert.equal(th?.regionCode,'tokai');const sk=findCity(data.catalog,'kurasushi','北海道','札幌市'),tk=findExact(data.catalog,'kurasushi','愛知県','豊橋市');assert.ok(sk&&tk);assert.notEqual(sk.officialUrl,tk.officialUrl);assert.ok(findExact(data.catalog,'musashimaru','愛知県','豊橋市'));assert.ok(findExact(data.catalog,'totomaru','愛知県','豊橋市'));}
function validateIndex(index){assert.match(index,/name="app-version" content="20260826-data-pwa1"/);assert.match(index,/class="app-scene"/);assert.match(index,/suruga-theme\.css/);assert.match(index,/local-tokai\.css/);assert.match(index,/id="prefectureSelect"/);assert.match(index,/id="citySelect"/);assert.match(index,/id="applyRegionBtn"/);assert.match(index,/id="regionStatus"/);assert.match(index,/id="chainQuickNavNational"/);assert.match(index,/id="chainQuickNavLocal"/);assert.match(index,/id="cardsNational"/);assert.match(index,/id="cardsLocal"/);assert.match(index,/serviceWorker\.register/);for(const id of ['uobei','totomaru','musashimaru','tokubei'])assert.match(index,new RegExp(`data-chain="${id}"`));assert.doesNotMatch(index,/id="todayHighlights"/);}
function validateNational(source){assert.match(source,/national fair|全国フェア/i);assert.match(source,/regionalPrice/);assert.match(source,/not_listed_reference_store/);assert.match(source,/ピックアップ：公式おすすめをメニューで確認/);assert.match(source,/availableInSelectedArea/);assert.match(source,/地域メニューを公式で確認/);}
function validateServiceWorker(source){for(const path of ['national.js','region.js','styles.css','region.css','brand.css','local-tokai.css','suruga-theme.css','manifest.webmanifest','suruga-bay-fuji-bg.webp'])assert.match(source,new RegExp(path.replace('.','\\.')));assert.match(source,/store-contexts\.json/);assert.match(source,/networkFirst/);assert.doesNotMatch(source,/app\.js/);}
function validateWebp(asset){assert.match(asset.type,/^image\/webp(?:;|$)/i);assert.ok(asset.bytes.length>1000);assert.equal(String.fromCharCode(...asset.bytes.slice(0,4)),'RIFF');assert.equal(String.fromCharCode(...asset.bytes.slice(8,12)),'WEBP');}
async function verifyOnce(a,local){const base=new URL(PAGE_URL);if(!base.pathname.endsWith('/'))base.pathname+='/';const remoteIndex=await fetchText(base.href,a);assert.equal(normalize(remoteIndex),normalize(local.index));validateIndex(remoteIndex);const remoteNational=await fetchText(new URL('national.js',base).href,a);assert.equal(normalize(remoteNational),normalize(local.national));validateNational(remoteNational);const remoteSw=await fetchText(new URL('sw.js',base).href,a);assert.equal(normalize(remoteSw),normalize(local.sw));validateServiceWorker(remoteSw);const bg=await fetchBinary(new URL('assets/suruga-bay-fuji-bg.webp',base).href,a);validateWebp(bg);const fairs=JSON.parse(await fetchText(new URL('data/fairs.json',base).href,a));const stores=JSON.parse(await fetchText(new URL('data/store-contexts.json',base).href,a));freshness(fairs.updatedAt,local.fairs.updatedAt,'fairs');freshness(stores.updatedAt,local.stores.updatedAt,'store-contexts');validateFairs(fairs);validateStores(stores);return{status:'ok',verifiedAt:new Date().toISOString(),testedCommit:process.env.GITHUB_SHA||null,pageUrl:base.href,publicStaticMatchesSource:true,publicDataAtLeastAsFresh:true,backgroundAssetOk:true,fairsUpdatedAt:fairs.updatedAt,storeContextsUpdatedAt:stores.updatedAt,chainCount:fairs.chains.length,localTokaiReady:LOCAL.every(id=>fairs.chains.some(x=>x.chain===id)),chains:Object.fromEntries(fairs.chains.map(x=>[x.chain,{fairName:x.fairName,itemCount:x.items.length,status:x.status,representativeImage:Boolean(x.representativeImageUrl||x.imageUrl)}]))};}
async function report(x){if(!REPORT_PATH)return;await fs.mkdir(path.dirname(REPORT_PATH),{recursive:true});await fs.writeFile(REPORT_PATH,JSON.stringify(x,null,2)+'\n');}
const local={index:await fs.readFile(path.join(ROOT,'app','index.html'),'utf8'),national:await fs.readFile(path.join(ROOT,'app','national.js'),'utf8'),sw:await fs.readFile(path.join(ROOT,'app','sw.js'),'utf8'),fairs:JSON.parse(await fs.readFile(path.join(ROOT,'app','data','fairs.json'),'utf8')),stores:JSON.parse(await fs.readFile(path.join(ROOT,'app','data','store-contexts.json'),'utf8'))};
let last=null;for(let a=1;a<=MAX_ATTEMPTS;a++){try{const r=await verifyOnce(a,local);await report(r);console.log('Published sushi app smoke test passed.');console.log(JSON.stringify(r,null,2));process.exit(0);}catch(e){last=e;console.warn(`Smoke attempt ${a}/${MAX_ATTEMPTS} failed: ${e.message}`);if(a<MAX_ATTEMPTS)await sleep(RETRY_DELAY_MS);}}throw last||new Error('Published app smoke test failed');
